# Generated by Django 4.1.1 on 2022-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='activity',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
