# Generated by Django 3.2.12 on 2022-09-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datainstance',
            name='activity',
            field=models.CharField(default='UNKNOWN', max_length=10, verbose_name='Activity'),
        ),
    ]
